project:
  type: book
  output-dir: docs
  
execute: 
  cache: false

book:
  title: "VieRnes de Bioinformática"
  author: 
    - Emilio Ortiz-Avila
  date: "11/18/2025"
  page-navigation: true
  chapters:
    - VectoresR.qmd
  # Information
  repo-url: https://github.com/Emilio-O/Viernes-Bioinfo-2026 # link de Github


format:
  html:
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: minty
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual
